language: php

php:
    - 7.1

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - composer self-update

install:
    - composer update --prefer-dist

before_script:
    - (cd tests/Application && bin/console doctrine:schema:create --env=test)

script:
    - composer validate

    - vendor/bin/behat --strict -vvv --no-interaction || vendor/bin/behat --strict -vvv --no-interaction --rerun
