sylius_grid:
    grids:
        babdev_sylius_supplier_admin_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: BabDev\SyliusSupplierBundle\Model\Supplier
            sorting:
                name: asc
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [name]
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
