babdev_sylius_supplier_admin_supplier:
    resource: |
        alias: babdev_sylius_supplier.supplier
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['delete']
        redirect: index
        grid: babdev_sylius_supplier_admin_supplier
        vars:
          all:
              subheader: babdev_sylius_supplier.ui.configure_your_store_suppliers
          index:
              icon: shopping bag
    type: sylius.resource

babdev_sylius_supplier_admin_supplier_bulk_delete:
    path: /bulk-delete
    methods: [DELETE]
    defaults:
        _controller: babdev_sylius_supplier.controller.supplier:bulkDeleteAction
        _sylius:
            section: admin
            redirect: referer
            permission: true
            paginate: false
            repository:
                method: findById
                arguments: [$ids]

babdev_sylius_supplier_admin_supplier_delete:
    path: /suppliers/{id}
    methods: [DELETE]
    defaults:
        _controller: babdev_sylius_supplier.controller.supplier:deleteAction
        _sylius:
            section: admin
