babdev_sylius_supplier_admin_supplier:
    resource: |
        alias: babdev_sylius_supplier.supplier
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: babdev_sylius_supplier_admin_supplier
        vars:
          all:
              subheader: babdev_sylius_supplier.ui.configure_your_store_suppliers
          index:
              icon: shopping bag
    type: sylius.resource
